### ISSUE TITLE
 建议合并计科和软工的大四部分

### ISSUE THREAD

**Issue by larry6799** [baolintian/XDU_CS_Learning#12]
计科和软工大四都没有课了，毕业设计也是一起的，保研，工作情况也都类似。建议将大四部分合并一起，下设子标题：保研/出国/工作/实习/毕业设计/实验室招生宣传

**Comment by zhouxuan009** [comment]
建议把合并的部分放到主目录下，方便后人找到

**Comment by baolintian** [comment]
> 计科和软工大四都没有课了，毕业设计也是一起的，保研，工作情况也都类似。建议将大四部分合并一起，下设子标题：保研/出国/工作/实习/毕业设计/实验室招生宣传

目前已经尽可能的合并，但是毕业设计模块还是放在了大四模块下，也不想将其独立为一个主目录。不知能否有更好的建议

**Comment by larry6799** [comment]
这样也挺好 毕业设计放到CS和EE目录，强调了学业的连贯性 。
